### ISSUE TITLE
Update client.py send_webhook_message() to match docs

### ISSUE THREAD

**Issue by Luunae** [ArjunSharda/nextguild#46]
Specifically:
https://github.com/ArjunSharda/nextguild/blob/5c53c5422b6a44838bfd2b279439c5327a33f2a5/nextguild/client.py#L1015-L1028

Per https://github.com/ArjunSharda/nextguild/blob/main/docs/ext/client/webhooks.rst , this function should also accept the optional arguments `embeds: list`, `username: str`, and `avatar_url: str`.

Additionally, `content` should simultaneously be changed to be optional here, to match the Guilded Webhook API ( https://guildedapi.com/resources/webhook/#jsonform-params ). Possibly with an in-function check to make sure one of `content` or `embeds` are provided?

**Comment by ArjunSharda** [comment]
Hi Luunae!

Thank you for bringing this to the team's attention! I'll work on this and change them. Thank you for reporting this!


Thanks,
Arjun

**Comment by ArjunSharda** [comment]
Update: Issue has been fixed, and will be implemented when pull request #49 is merged for the next update. Thank you to everybody who participated in this.

Issue will be closed upon merge of the pull request.
